[
  [{
    "key": "actorIntro",
    "requiredTypes": [
      "agent"
    ],
    "texts": [
      "%agent is a mysterious being roaming the galaxy in search of a lost soul."
    ]
  }],
  {
    "key": "revenge",
    "requiredTypes": [
      "agent"
    ],
    "texts": [
      "The betrayal felt by %agent drives him to seek revenge against all that wronged him.",
      "%agent felt betrayed. He is acting out of pure hatred and seeks revenge at all costs."
    ]
  }
]