[
  {
    "key": "nuggetB",
    "requiredTypes": [],
    "texts": [
      "B."
    ]
  },
  {
    "key": "nuggetTestEntity",
    "requiredTypes": [
      "TestEntityType"
    ],
    "texts": [
      "a %TestEntityType"
    ]
  },
  {
    "key": "complexNugget",
    "requiredTypes": [
      "TestEntityType",
      "location"
    ],
    "texts": [
      "a %TestEntityType at %location"
    ]
  },
  {
    "key": "nuggetTestWrongType",
    "requiredTypes": [
      "TestEntityType"
    ],
    "texts": [
      "This is %NotMyType"
    ]
  }
]