language: cpp

install:
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.2.tar.gz
  - tar -xzvf cmake-3.3.2.tar.gz
  - cd cmake-3.3.2 && ./configure --prefix=$HOME/cmake && make && make install

compiler:
  - gcc

before_script:
  - mkdir -p bin
  - $HOME/cmake/bin/cmake -version
  - $HOME/cmake/bin/cmake ($pwd)

script:
  - make
  - ./bin/QuestWeaverTest
