[
  {
    "key": "simpleLine",
    "required": [],
    "lines": [
      {
        "pre": "A.",
        "nuggets": [
          "nuggetB"
        ],
        "post": "C"
      }
    ]
  },
  {
    "key": "entityLine",
    "required": [
      "TestEntityType"
    ],
    "lines": [
      {
        "pre": "I wish me",
        "nuggets": [
          "nuggetTestEntity"
        ],
        "post": "to play with."
      }
    ]
  },
  {
    "key": "stringOnlyLines",
    "required": [],
    "lines": [
      "This is great!",
      "I really love this."
    ]
  },
  {
    "key": "partialLines",
    "required": [],
    "lines": [
      {
        "pre": "This is"
      },
      {
        "post": "the result of"
      },
      {
        "pre": "some",
        "post": "partial lines."
      }
    ]
  },
  {
    "key": "unknownNugget",
    "required": [],
    "lines": [
      {
        "pre": "X",
        "post": "Z",
        "nuggets": [
          "thisIsSomeNugget"
        ]
      }
    ]
  },
  {
    "key": "wrongNuggetIds",
    "required": [],
    "lines": [
      {
        "pre": "X",
        "post": "Z",
        "nuggets": [
          "complexNugget"
        ]
      }
    ]
  },
  {
    "key": "wrongNuggetContent",
    "required": [
      "TestEntityType"
    ],
    "lines": [
      {
        "pre": "X",
        "post": "Z",
        "nuggets": [
          "nuggetTestWrongType"
        ]
      }
    ]
  }
]