[
  {
    "key": "agentIntro",
    "required": ["agent"],
    "text": "[actorIntroMysterious|actorIntroMachine:1] {actorUnknownOrigin:1}{logEntry}"
  },
  {
    "key": "locationIntro",
    "required": ["solarSystem"],
    "text": "[locationStrangeGravity|locationBattle:1]{logEntry}"
  },
  {
    "key": "planetIntro",
    "required": [
      "planet"
    ],
    "text": "[planetVeryOld|planetVeryYoung|planetCuddlyCreatures:1]{planetMetals}{planetLife}{logEntry}"
  },
  {
    "key": "shipIntro",
    "required": [
      "spaceShip"
    ],
    "text": "[shipOriginOwner:shipAndOwner]{logEntry}"
  }
]
