[
  {
    "key": "empty",
    "requiredTypes": [],
    "texts": [
      ""
    ]
  },
  {
    "key": "actorIntroMysterious",
    "requiredTypes": [
      "agent"
    ],
    "texts": [
      "%agent is a mysterious being roaming the galaxy in search of a lost soul."
    ]
  },
  {
    "key": "actorUnknownOrigin",
    "requiredTypes": [
      "agent"
    ],
    "texts": [
      "It is not known where %agent originated from.",
      "It is not known where %agent originated from, but several clues suggest that the location lies beyond our known galaxy.",
      "It is not known where %agent originated from, but several clues suggest that the location lies in our known galaxy.",
      "Our databanks do not contain any information on the origin of %agent.",
      "Our databanks do not contain any conclusive information on the origin of %agent.",
      "Our databanks do not contain any information on the origin of %agent. It looks like someone recently deleted that information, which is rather strange."
    ]
  },
  {
    "key": "revenge",
    "requiredTypes": [
      "agent"
    ],
    "texts": [
      "The betrayal felt by %agent drives him to seek revenge against all that wronged him.",
      "%agent felt betrayed. He is acting out of pure hatred and seeks revenge at all costs."
    ]
  }
]