[
  {
    "key": "empty",
    "requiredTypes": [],
    "texts": [""]
  },
  {
    "key": "actorIntroMysterious",
    "requiredTypes": ["agent"],
    "texts": ["%agent is a mysterious being roaming the galaxy in search of a lost soul."]
  },
  {
    "key": "actorIntroMachine",
    "requiredTypes": ["agent"],
    "texts": [
      "%agent appears to be a sentient machine, which outlived its creators.",
      "%agent appears to be a sentient machine, but the creator is unknown."
    ]
  },
  {
    "key": "actorUnknownOrigin",
    "requiredTypes": ["agent"],
    "texts": [
      "It is not known where %agent originated from.",
      "It is not known where %agent originated from, but several clues suggest that the location lies beyond our known galaxy.",
      "It is not known where %agent originated from, but several clues suggest that the location lies in our known galaxy.",
      "Our databanks do not contain any information on the origin of %agent.",
      "Our databanks do not contain any conclusive information on the origin of %agent.",
      "Our databanks do not contain any information on the origin of %agent. It looks like someone recently deleted that information, which is rather strange."
    ]
  },
  {
    "key": "logEntry",
    "requiredTypes": [],
    "texts": ["[Datalog Entry 2846219]", "[End of datalog Entry]"]
  },
  {
    "key": "locationStrangeGravity",
    "requiredTypes": ["location"],
    "texts": [
      "The star system known as %location was only discovered very recently. Due to an unknown phenomenon, it has an unusual amount of gravity lenses positioned around it, hiding it from cursory sensor scans.",
      "The star system %location produced such strange gravitational readings, that the ship first reported malfunctioning sensors. The cause of this is still unknown."
    ]
  },
  {
    "key": "revenge",
    "requiredTypes": ["agent"],
    "texts": [
      "The betrayal felt by %agent drives him to seek revenge against all that wronged him.",
      "%agent felt betrayed. He is acting out of pure hatred and seeks revenge at all costs."
    ]
  }
]